### ISSUE TITLE
Bad gameplay written in a bad language

### ISSUE THREAD

**Issue by Nnmjywg** [XerneraC/Tic-Tac-Toe#2]
I highly disagree with the “frame-by-frame” approach that you took. It makes it hard to concentrate on gameplay. I also disagree with approach that you took for user input. However, the terminal is a terrible medium for games as it is, so this is somewhat understandable.

Why not write your game with pygame, which is really a python wrapper for SDL, which in turn is written in C? Good question! It’s because you can just write your game in C and SDL to begin with, and end up with a better game that uses a tenth of the memory used by the OO garbage in python.

**Comment by 0x000C0A71** [comment]
C is extremely bloated. I‘ll write it in assembly
